# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 16:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oferta', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('cognoms', models.CharField(max_length=200)),
                ('naixement', models.DateField(null=True)),
                ('dni', models.CharField(max_length=9)),
                ('adreca', models.CharField(max_length=250)),
                ('poblacio', models.CharField(max_length=50)),
                ('cp', models.CharField(default=12345, max_length=5)),
                ('nif', models.CharField(max_length=8)),
                ('estudis', models.TextField()),
                ('idiomes', models.TextField()),
                ('imatge', models.ImageField(default='perfil/default.gif', upload_to='perfil/')),
                ('ofertesPreferides', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferta.Oferta')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
